[project]
name = "onnx-asr-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.1",
    "jiwer>=4.0.0",
    "torch>=2.9.1",
    "torchcodec>=0.9.1",
    "vistreamasr>=0.1.3",
]
